#!/bin/sh
rm -rf temp
mkdir temp;cd temp
mvn archetype:generate -B -DarchetypeGroupId=org.appfuse.archetypes -DarchetypeArtifactId=appfuse-basic-struts-archetype -DarchetypeVersion=3.5.0 -DgroupId=org.appfuse.tutorial -DartifactId=tutorial-hibernate -DarchetypeRepository=http://oss.sonatype.org/content/repositories/appfuse
mvn archetype:generate -B -DarchetypeGroupId=org.appfuse.archetypes -DarchetypeArtifactId=appfuse-basic-struts-archetype -DarchetypeVersion=3.5.0 -DgroupId=org.appfuse.tutorial -DartifactId=tutorial-jpa -DarchetypeRepository=http://oss.sonatype.org/content/repositories/appfuse
mvn archetype:generate -B -DarchetypeGroupId=org.appfuse.archetypes -DarchetypeArtifactId=appfuse-basic-struts-archetype -DarchetypeVersion=3.5.0 -DgroupId=org.appfuse.tutorial -DartifactId=tutorial-service -DarchetypeRepository=http://oss.sonatype.org/content/repositories/appfuse
mvn archetype:generate -B -DarchetypeGroupId=org.appfuse.archetypes -DarchetypeArtifactId=appfuse-basic-jsf-archetype -DarchetypeVersion=3.5.0 -DgroupId=org.appfuse.tutorial -DartifactId=tutorial-jsf -DarchetypeRepository=http://oss.sonatype.org/content/repositories/appfuse
mvn archetype:generate -B -DarchetypeGroupId=org.appfuse.archetypes -DarchetypeArtifactId=appfuse-basic-spring-archetype -DarchetypeVersion=3.5.0 -DgroupId=org.appfuse.tutorial -DartifactId=tutorial-spring -DarchetypeRepository=http://oss.sonatype.org/content/repositories/appfuse
mvn archetype:generate -B -DarchetypeGroupId=org.appfuse.archetypes -DarchetypeArtifactId=appfuse-basic-struts-archetype -DarchetypeVersion=3.5.0 -DgroupId=org.appfuse.tutorial -DartifactId=tutorial-struts -DarchetypeRepository=http://oss.sonatype.org/content/repositories/appfuse
mvn archetype:generate -B -DarchetypeGroupId=org.appfuse.archetypes -DarchetypeArtifactId=appfuse-basic-tapestry-archetype -DarchetypeVersion=3.5.0 -DgroupId=org.appfuse.tutorial -DartifactId=tutorial-tapestry -DarchetypeRepository=http://oss.sonatype.org/content/repositories/appfuse
mvn archetype:generate -B -DarchetypeGroupId=org.appfuse.archetypes -DarchetypeArtifactId=appfuse-basic-wicket-archetype -DarchetypeVersion=3.5.0 -DgroupId=org.appfuse.tutorial -DartifactId=tutorial-wicket -DarchetypeRepository=http://oss.sonatype.org/content/repositories/appfuse
